version = "1.3.0"
builder = "spa"

[template_settings]
text-color = "#c7cfcc"
accent-color = "#2D4566"
background-color = "#121414"
highlight-color = "#73bed3"
autoreload = "1"
custom-color = "#f3a833"
youtube-embed-params = "autoplay=1"
